services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    init: true
    volumes:
      - type: bind
        source: ./api
        target: /usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped